### ISSUE TITLE
Translation to portuguese

### ISSUE THREAD

**Issue by G4L1T0** [c0rdis/security-champions-playbook#3]
Hello! I'm studying more about the security champions process and found this repository.
I would like to translate it into Portuguese, I believe this content can be very useful for many people!

Would there be any problem with that? Can I make this translation and do the PR?

I'm waiting for your reply!

**Comment by c0rdis** [comment]
Hi @G4L1T0, thanks for your interest in the playbook! Translating it to Portuguese sounds amazing, please feel free to do so and do the PR, we'd be happy to add you as our collaborator :)

Cheers!

**Comment by G4L1T0** [comment]
Hey @c0rdis! A doubt, what does BTS mean in the table [here](https://github.com/c0rdis/security-champions-playbook/blob/master/Security%20Playbook/1.%20Identify%20teams.md#1-identify-teams) ?


![Captura de Tela 2023-08-01 às 10 38 41](https://github.com/c0rdis/security-champions-playbook/assets/91551911/5fbfc23a-76ab-49ff-b63f-a947c2f8c0e7)

**Comment by c0rdis** [comment]
Hey, it refers to bug tracking system (Jira) project
